<?php

/**
 * Implementation of hook_block_info()
 * provides a Socialshare privacy as block
 * @return array
 */
function secureshare_blocks_block_info() {
  $blocks = array();

  $blocks['secureshare_block'] = array(
    'info' => t('Socialshare privacy'),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_configure()
 * provides block settings for Socialshare privacy.
 * @param string $delta
 * @return array
 */
function secureshare_blocks_block_configure($delta = '') {
  $form = array();
  if ($delta === 'secureshare_block') {
    // include the admin forms from core module and proceed if success
    if (module_load_include('inc', 'secureshare', 'secureshare.admin')) {
      // merge in admin form
      $form += secureshare_settings_form();

      //@TODO: we need to merge in the default values
    };
  }
  return $form;
}

/**
 * Implementation of hook_block_save()
 * @param string $delta
 * @param array $edit
 */
function secureshare_blocks_block_save($delta = '', $edit = array()) {
  if ($delta === 'secureshare_block') {

  }
}

/**
 * Implementation of hook_block_view
 * @param string $delta
 * @return array
 */
function secureshare_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'secureshare_block':
      $block['subject'] = t('Secureshare overall block');
      $block['content'] = array(
        'securesharelement' => array(
          '#type' => 'secureshare',
          '#secureshare_options' => array(),
        ),
      );
    break;
  }

  return $block;
}
